"""Pure functions for classifying and reporting data-quality results.

Deliberately free of any database dependency: it takes plain dictionaries in and
returns strings out. That makes it unit-testable without a warehouse, which is
the whole reason the logic lives here instead of inline in quality_checks.py.
"""

from __future__ import annotations


def classify(severity: str, failed_rows: int, baseline: int) -> str:
    """Decide the status of one check result.

    PASS      - nothing violates the rule
    WARN      - tolerable by design; never stops the build
    ACCEPTED  - a known defect at or below its documented baseline
    FAIL      - a REGRESSION: worse than the baseline we signed off on
    """
    if failed_rows == 0:
        return "PASS"
    if severity == "WARN":
        return "WARN"
    if failed_rows <= baseline:
        return "ACCEPTED"
    return "FAIL"


def build_report(results: list[dict]) -> str:
    """Render the results as the markdown of outputs/dq_report.md."""
    fails = [r for r in results if r["status"] == "FAIL"]
    warns = [r for r in results if r["status"] == "WARN"]
    accepted = [r for r in results if r["status"] == "ACCEPTED"]
    passed = [r for r in results if r["status"] == "PASS"]

    lines = [
        "# Data Quality Report",
        "",
        f"Checks run: **{len(results)}** &nbsp;|&nbsp; "
        f"Clean: **{len(passed)}** &nbsp;|&nbsp; "
        f"Accepted: **{len(accepted)}** &nbsp;|&nbsp; "
        f"Warnings: **{len(warns)}** &nbsp;|&nbsp; "
        f"Regressions: **{len(fails)}**",
        "",
        "> Generated by `python -m src.quality_checks`. Overwritten on every run,",
        "> so it always reflects the current state of the raw layer.",
        "",
        "**Status meanings**",
        "",
        "- `PASS` - no rows violate the rule.",
        "- `ACCEPTED` - a known defect, at or below its documented baseline in",
        "  `config/config.yml`, with a stated resolution applied in staging.",
        "- `WARN` - tolerable, tracked, does not stop the build.",
        "- `FAIL` - **regression**: worse than the accepted baseline. Stops the build.",
        "",
        "## Summary",
        "",
        "| Check | Entity | Rows | Baseline | Status |",
        "|---|---|---|---|---|",
    ]
    for r in results:
        badge = f"**{r['status']}**" if r["status"] == "FAIL" else r["status"]
        lines.append(
            f"| `{r['check_id']}` | {r['entity']} | {r['failed_rows']:,} | "
            f"{r['baseline']:,} | {badge} |"
        )

    if fails:
        lines += ["", "## Regressions (pipeline stopped)", ""]
        for r in fails:
            lines += [
                f"### `{r['check_id']}`", "",
                f"- **Rule:** {r['check_name']}",
                f"- **Entity:** `{r['entity']}`",
                f"- **Rows:** {r['failed_rows']:,} (baseline {r['baseline']:,})",
                f"- **Detail:** {r['detail']}",
                f"- **Query:** [`sql/quality/{r['file']}`](../sql/quality/{r['file']})",
                "",
            ]

    if accepted:
        lines += ["", "## Accepted defects, and how staging resolves each one", ""]
        lines += ["| Check | Rows | Resolution |", "|---|---|---|"]
        for r in accepted:
            lines.append(f"| `{r['check_id']}` | {r['failed_rows']:,} | {r['resolution']} |")
        lines.append("")

    if warns:
        lines += ["", "## Warnings (pipeline continued)", ""]
        for r in warns:
            lines += [
                f"### `{r['check_id']}`", "",
                f"- **Rule:** {r['check_name']}",
                f"- **Rows affected:** {r['failed_rows']:,}",
                f"- **Detail:** {r['detail']}",
                f"- **Query:** [`sql/quality/{r['file']}`](../sql/quality/{r['file']})",
                "",
            ]

    lines += [
        "",
        "## How to read this",
        "",
        "Every defect listed here was deliberately injected by",
        "`src/generate_data.py` - see `docs/data_dictionary.md` section 7 for the",
        "full catalogue. The point of this project is not that the data is clean;",
        "it is that the pipeline *proves* what is wrong with it, in writing,",
        "before anyone builds a metric on top of it.",
        "",
        "The baselines in `config/config.yml` turn this from a one-off audit into a",
        "**regression test**: the build passes today, and breaks the moment the data",
        "gets worse than the state we knowingly signed off on.",
    ]
    return "\n".join(lines)
